# Exceptions messages
exception:
  user:
    not-exist: "User not exist"
    wrong-password: "Wrong password"
  token:
    is-null: "User not authorized"
    for-another-user: "Authorized another user"
    wrong: "Token is wrong"
  message:
    not-exist: "Message history is empty"
# Constants
app:
  jwt-secret: "lav-valentine-secret-key_lav-valentine-secret-key"
  message-getting-first-10: "history 10"